version: "3.8"

services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
    volumes:
      - "./.mysql_data_dir:/var/lib/mysql/"

  zk:
    image: debezium/zookeeper:1.2
    # ports:
    #   - "2181:2181"
    #   - "2888:2888"
    #   - "3888:3888"

  kafka:
    image: debezium/kafka:1.2
    ports:
      - "9092:9092"
    environment:
      - "ZOOKEEPER_CONNECT=zk:2181"
      # - "ADVERTISED_HOST_NAME=localhost:9092"

  connect:
    image: debezium/connect:1.2
    ports:
      - "8083:8083"
    environment:
      - "BOOTSTRAP_SERVERS=kafka:9092"
      - "CONFIG_STORAGE_TOPIC=my_connect_configs"
      - "OFFSET_STORAGE_TOPIC=my_connect_offsets"
      - "STATUS_STORAGE_TOPIC=my_connect_statuses"
